name: money_track_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.1
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1
  carousel_slider: ^4.2.1
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  lottie: ^2.6.0
  device_info_plus: ^9.1.1
  google_sign_in: ^6.1.6
  syncfusion_flutter_charts: ^22.2.12

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
